services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    ports:
      - "8080:8080"
    restart: unless-stopped

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - searxng 
    env_file:
      - ../.env
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
